apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:7ogvdOU=,iv:azyvJ8ei/Rrk5j2ROfMV4jTIY5ic9Ownw1atw1FSEAY=,tag:cUoThwI7nzehWXV0BCriYA==,type:str]
    admin-password: ENC[AES256_GCM,data:mAwJAUtzgnAPBXaBlfQ=,iv:SWH3VYOEvwbAqJ8noVacGcLrnLWu1qf8Bi4EhExJS+o=,tag:Q0e1wgqZVFczZ8RkEB0uQA==,type:str]
sops:
    age:
        - recipient: age1wf5fe39ddk2dwh5ute445pfsv3wl68hx2j7f9phh90zvgnsk8sdsdj0zx7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OUVIQ2hWVThzNnQvakM3
            emozdkhtSUJlUkhtOHNpblo4UHhYR3kySEE4CnluTVZodEJ4c3F5RGFKVW5zWW5O
            OHYzZTNSQWNvK0kvRWNKM3RhRWlyQWcKLS0tIExDdGJBZGkvdE1QUlFJSUs1bXVF
            TWVIZG5SQ0lUbUZUcW1pVnhoTFJvV2sKmM+eDDySrTfuUUHtdGjwW1JIK0ES9bZS
            eMwMC6EFx7zJM01DgmyGxGmoGZ9Mf0xNwHvkSfsYecXxHU6i/WvWJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T09:00:37Z"
    mac: ENC[AES256_GCM,data:GRWfRM8nfY6n/pCQxUiZlPCg5+7r3IXOcG/pqQrGUeNEi4IUwpIWoQfKkJqMm4fikMWcyaxoTtU6JtpPo1RBoArqa/a4ZK2jgGwZj5TwMZIhfNVCoWwrEWfq8seVyBUsb5ied9aJoTzn71jBeE3umpcy+ln39ZKV8IcpXFRQaGg=,iv:hk4pXekcMKcyjSYAStWJDXaUQHY8ogcea6OYwARMVYg=,tag:zx5vKdQUYJB9bc/+iHCz9Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
