apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
  namespace: couchdb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      nodeSelector:
        kubernetes.io/hostname: asus-8gb
      securityContext:
        runAsUser: 5984
        runAsGroup: 5984
        fsGroup: 5984
      containers:
        - name: couchdb
          image: couchdb:3
          ports:
            - containerPort: 5984
          env:
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: couchdb-secret
                  key: COUCHDB_USER
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb-secret
                  key: COUCHDB_PASSWORD
          volumeMounts:
            - mountPath: /opt/couchdb/data
              name: couchdb-data
            - mountPath: /opt/couchdb/etc/local.d
              name: couchdb-etc
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 512Mi
      volumes:
        - name: couchdb-data
          persistentVolumeClaim:
            claimName: couchdb-data
        - name: couchdb-etc
          persistentVolumeClaim:
            claimName: couchdb-etc
---
apiVersion: v1
kind: Service
metadata:
  name: couchdb
  namespace: couchdb
spec:
  selector:
    app: couchdb
  ports:
    - port: 5984
      targetPort: 5984
