apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:hUMeDK0EXi8RHG8avrbICYnzxklkSqtYMo93g70c5e9P07huKYFxtEJwIcyYpuDf0nn+mILqmk6MoJdF5LSGfDnnjKvj,iv:4Io8gPH647rOB/8IEVPeIAbsjykpgio3tnrwkqZbLv0=,tag:3jm6ZUkavOz2ipZW/dkPYA==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:Wf1sGB3AvAcG,iv:MR9O6iNhEQwWU4rJ6jV9pfQWTqb6g7nd/inI2P9z/uk=,tag:EGTxUanp/cTrdKISeKRhNw==,type:str]
    AUTHENTIK_REDIS__PASSWORD: ENC[AES256_GCM,data:i1md5KR3nVsj,iv:/ei7tsibr9q8buyEURLboP6A1UAdMESFhxBXKY77p7o=,tag:tYtIA9iF1CiN2CMokZoRpw==,type:str]
sops:
    age:
        - recipient: age1wf5fe39ddk2dwh5ute445pfsv3wl68hx2j7f9phh90zvgnsk8sdsdj0zx7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXekNlNENoc29DK2pZUmlW
            U01tUzRQN0dZUkEzNFFScEJmMGd2MGs2WERVCnpNR29aUHIvTnNPR1RIWnhld1p4
            NEhxRGxGQTJmZS84WTFDUlFxOXFoZDQKLS0tIGlpQlVxL2QzOGpYN1NjcTRzdW8v
            Q0JLLzlSY01selNoZUQ5NElrSmtyc3MKsCdP9lrxOibc6qJAwTmvOVDkAW/T7Zpt
            eAhwb9C2TEa9ewh0ARXSNb8YnSe+x3LpfFIBnJx+BD5/pu86O81tGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T12:37:05Z"
    mac: ENC[AES256_GCM,data:J8V03h/T4R2Ul1na14KLDvE2mE21gRnGl4uIc7bn4u9HIsl18fjB+jjcsAaJk3ixz33S18CRfdrKAKTeUIMM3QleN7Ey+Tdbjwv6GvgcX+gelQzugCw+zzqzRAmM9T8sbqJ8NUUJ5B2zoiQG/KXV7ENYSzb+U2KSGZD0xBZeOO0=,iv:ExQAMdJc3/tm1v7VT54QoT8XVFM4CH4iTsgf41HUArU=,tag:pioyikGroks2NLJbyBlPZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
