apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:ERbV4Y3ypsi/dAxADU5AoPCe5R4VfddFL2ao2Z71AlZfyxvyzxB8pXiybm03MtFXSCeZSFh67jzSxYNZYF/OCL67QG7Z,iv:HF0J+GPOGB95ygziQXlPBQ1PtL4av7xPZWT1iLwujC8=,tag:Tby5utpnwR1q/EvJXwTJxg==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:DMrnWCBYk4EK,iv:YFc9Hf0uijwUvsqu3eec589t2AnOe0YskZkCyZj+F2c=,tag:gQ85xEhdYC/lnlyjbyxelg==,type:str]
sops:
    age:
        - recipient: age1wf5fe39ddk2dwh5ute445pfsv3wl68hx2j7f9phh90zvgnsk8sdsdj0zx7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWGlDcGd3Yk9sYWQyOWkw
            ZlRNTzFSMkRhdCsrSFlFTUtCT0x4OXUxNVNVClk1REQwVDRUMzJsZE1MTGxsdzFw
            YmhYSnA1YUR4V0I0VEVRNUd1aFNwZDgKLS0tIFd4cngwd01xUUgrSHU5b2ppUFU0
            V2p3RUJ4b0FXSXBMN0tuSHl3UGF2dVUKtmGrKu/3rTFD71nVtpCSwNuf7Ug6Gpqs
            wUK44whSotsbw7nj1bR5CGrM2P/1qF9H0IFbQfDmeOV3Dl5GW5v23A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T12:41:44Z"
    mac: ENC[AES256_GCM,data:zDrS/XXATWcH+vQmmkUSdLrLZZfKEsCqdYrLT1iDN4/UmTou0txk5nzy+wkYV1JkKdu9G/ItndMKQMCWfBLGkc1cyM/gyhZectny9EAwLvPaiGMejmRmaLJkvQ0Y0/coneQbiYB9R7TVSNeRGbT9xXLwaaYmQskgYL82VZojsTg=,iv:4K9cNFgsYyhJX+F8i2fO75SG/8i0WH7ErxqWpOKBwto=,tag:Q2lodSTGx9zUBvdezAPg0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
