apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-postgres
  namespace: paperless
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: paperless-postgres
  template:
    metadata:
      labels:
        app: paperless-postgres
    spec:
      nodeSelector:
        kubernetes.io/hostname: asus-4gb
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: paperless
            - name: POSTGRES_USER
              value: paperless
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: PAPERLESS_DBPASS
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: paperless-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: paperless-postgres
  namespace: paperless
spec:
  selector:
    app: paperless-postgres
  ports:
    - port: 5432
      targetPort: 5432
