apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless
stringData:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:dbXNtJ+6Yyjn,iv:kZftckD1hp/hJUKHkpomLG5Gu3ZHgFXyJF0ZuNh2KNw=,tag:5dCvRJBcMoEZI5UvwBwXAQ==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:KXzXAfD0+lD9Jnho0YmsbWQU0BPS2ot+ZaljUsmunc8LqT/fxdP4pwdDaA5HLbz0FTk5cQckXiP+bkqlUv9tUIxJlSy/,iv:j2eoEP3zaQ5GoK7iAXCCdJiburt/R+AQBZq5pb0mcRo=,tag:CNFstUqSBjmxbY0fUxj8sA==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:MPxBcIg=,iv:ulmXER5gJkG2hwuwGSI+JkXMyz9TnQ5IWfiIkxy+IZ0=,tag:xtwb5Wcim3E+AfSEW7LKQA==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:01/6jnyd2Fa5uI/FTnk=,iv:trWu+mEDQqjRLSvSRo8h1yMkupQfeKK1+D7aM1iPDkA=,tag:ClUTpE+iOw4EKd1gSVRWEg==,type:str]
    PAPERLESS_ADMIN_MAIL: ENC[AES256_GCM,data:nhVE45/4SWt6K9nUTJ+qA80q,iv:cCYfhYKFJPBHuwuUbfwLMMt0jvCyU2KA17OCoaB5LP0=,tag:Bfw7tjF1FQQ8KU/NHN0Sig==,type:str]
sops:
    age:
        - recipient: age1wf5fe39ddk2dwh5ute445pfsv3wl68hx2j7f9phh90zvgnsk8sdsdj0zx7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZlFTNXA0S2R0SUE1MWRU
            RUZYQXBBQ2dRbGRNcmc4d3IxcmFjcHZUSjJVCllBWVJ1MmpYcmpqT2dSMUF2L2pk
            Y1VhRm9CSVZMSC9RNEx2RzcrQStmWVEKLS0tIHEvRjBJYm8yNHBra0dRNWEzZG9z
            Y2lTODA3dHZtOHZ3eU1LVFRFUHZLLzgKx6BLPsPQlbSCbuf/+bL3UowiM6/Szld6
            1q5gZMFd7jqekjw+Y7UoaKiaMvGjlA5rKVbBj5mIzOkJOL/8NOrZZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T17:16:14Z"
    mac: ENC[AES256_GCM,data:MyK2PhAkw3xrygfGQSTEWZXaEG0xyQuTZODl0nZBvbmSLArbdUcn75Wo1Gk1VuOE7adAasUVtwAgHTEgaeQyV6Po3eyFM33QjxNA/Kl/ZgxG046qXLStl2reZ79wfqaUkkUk/yJ1GuACLFZ+OVgrZuTsoTqN3bu4aQV4FhObQI4=,iv:EriYmj1V1KD4l4l7U8RYmoiIInQAeiCYKICyhJ/F2J0=,tag:iyQdLAqUPQa8GIWSE9ROSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
