apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless
stringData:
    paperless-user: ENC[AES256_GCM,data:kMfi93A=,iv:wbew2NxC9r616VGCU9w6EYGLCKptZePKTVpFyVfHwjU=,tag:MUJTwuT2UdJXssXySMXOWQ==,type:str]
    paperless-pass: ENC[AES256_GCM,data:BoZ5U6g2mUzPI3Kd8mw=,iv:JqyPYkLFMNlAyt0dN3eDjV2/eerdkFoUeWLHNxOyTqE=,tag:kZCBwCNfi0TqJPVecSoq6A==,type:str]
    paperless-mail: ENC[AES256_GCM,data:2Dkz/QZoQKGOVzZMx0rV2tsO,iv:9kg+EotPUXfzBTi6f3ITElGGNBCjd0mozlM5I96UyZ4=,tag:cT03Gp9+pfAE4uSbl/28IQ==,type:str]
sops:
    age:
        - recipient: age1wf5fe39ddk2dwh5ute445pfsv3wl68hx2j7f9phh90zvgnsk8sdsdj0zx7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdjFiU3dxdUs4V25tUk1u
            N0l6TlVrVjFJbHRrYTlHdkFRQUtqTmlIZnpNClhrUVZ5b01NeWtZY3hMWE05Zks1
            VVFhUjJ2VjRIK013Wk9ya1Z5SXZuZWMKLS0tIHNuYmk5V1lkd0FKRGFHYlJYVjJ1
            clpHU2gzVjhPOE1zVmNuc05WYUlseVkKG/wRPCHTmeMAdbmp/rnLNCxJIHb49wBe
            k4GQ7//1DPuzjM5VXbVuLlE1FDH3/nIKyTT6QwsxXdDwVq7qB5QKhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T16:40:54Z"
    mac: ENC[AES256_GCM,data:UwUCCcpXdhatdKGrpAKuJILa+qH7WIWOU8FxnuHcRinJarypmG1PVQGT+wFe5fdVagdxFaRbrgKs9+LLmCR+tQjU5t31XLmbNuZGmQ06hMX6pdEneNEdSs1rlPauavYs0opcjSeLelqgA6sAKcUD1qe+aKDJJRTyF7vQMKd+OIs=,iv:EV0hpB0rBpYiEfQ3hYEawspnTWPuZ6zXJgYFXv5n1n4=,tag:CotXDM956up2B0cJRn9sgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
