apiVersion: v1
kind: Secret
metadata:
    name: couchdb-secret
    namespace: couchdb
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:PfnB,iv:G+wKgUwP55Zh1A6lNQ1lo633F9Otn3eV82DjXOVYFZg=,tag:mwthErqI7IP7ElaKBZY/dQ==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:676VOgfvmKgla0RvXiY=,iv:GVfamnp3Gt0NLopIHghR3RHV9fAcDYPAmCbziul64+M=,tag:RE05UBiDPOVUpxJthhd6qA==,type:str]
sops:
    age:
        - recipient: age1wf5fe39ddk2dwh5ute445pfsv3wl68hx2j7f9phh90zvgnsk8sdsdj0zx7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQjFKOFFCR0htMHJGWlBK
            a2hua3pKbG40bGN0ajgzM1JNeU9TZnJtcHpzClhvQjhBWHJOT2NhSFVxZ1ZQRWdC
            V0FiTmNZVU5LL2UrR0hpQnllNGtNbDAKLS0tIFpuanFIWVpScFhzb0J5dXNvYU44
            Ujg1VEpBcVdmVUFrMmRYcEVyd3ZTTlEK4//fz4hoyAptMtOcXwPHlGlVvOrGuhct
            flIKuSgzteIzaMx1MLmSvnC+uWrxgUHffXHOM1ztimrqHxgREzcX6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T18:09:13Z"
    mac: ENC[AES256_GCM,data:FZijQAdMLib37vD6tvy4w4jhDu/XoXwVuOjoE+9owJ2P8Jbp2/5xNrZjXp0BrIt9cJIep6LEap8yLbw4kIKbERHGGGpbvWIQKh/Jb7P3oL8m7wb7+4o6lfSgqvyK2Y8QceJF5ImdedwmIoMdxe+WtnmZ5+KZPB0ZpKUsMJWd5rs=,iv:vXIORuUrdepR83ttgkzqZyJ+OBlZhKJMf0/N+JfCfBs=,tag:vA8a6K8/p5jSFB41o+kCuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
