apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-spotify-server
  namespace: your-spotify
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: your-spotify-server
  template:
    metadata:
      labels:
        app: your-spotify-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: asus-4gb
      containers:
        - name: server
          image: yooooomi/your_spotify_server:latest
          ports:
            - containerPort: 8080
          env:
            - name: API_ENDPOINT
              value: "https://spotify-api.cojusna.top"
            - name: CLIENT_ENDPOINT
              value: "https://spotify.cojusna.top"
            - name: SPOTIFY_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: your-spotify-secret
                  key: SPOTIFY_CLIENT_ID
            - name: SPOTIFY_SECRET
              valueFrom:
                secretKeyRef:
                  name: your-spotify-secret
                  key: SPOTIFY_CLIENT_SECRET
            - name: MONGO_ENDPOINT
              value: "mongodb://your-spotify-mongo:27017/your_spotify"
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: your-spotify-server
  namespace: your-spotify
spec:
  selector:
    app: your-spotify-server
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-spotify-web
  namespace: your-spotify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-spotify-web
  template:
    metadata:
      labels:
        app: your-spotify-web
    spec:
      nodeSelector:
        kubernetes.io/hostname: asus-4gb
      containers:
        - name: web
          image: yooooomi/your_spotify_client:latest
          ports:
            - containerPort: 3000
          env:
            - name: API_ENDPOINT
              value: "https://spotify-api.cojusna.top"
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: your-spotify-web
  namespace: your-spotify
spec:
  selector:
    app: your-spotify-web
  ports:
    - port: 3000
      targetPort: 3000
