apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: your-spotify-mongo
  namespace: your-spotify
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
