apiVersion: v1
kind: Secret
metadata:
    name: your-spotify-secret
    namespace: your-spotify
stringData:
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:xM2bnEIifOLSohJLHyebjjh4jIPszUpHag//KQUinu8=,iv:dgMPdn3eSbEPwa1jr9kcze+JvKMe+EX8Y5XLrxskoKI=,tag:3bIWaJ54Si98QnnGeiislg==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:WkcGa4CSheczkA6oIvicagZSx6jeQN+y4V2voOB8VsE=,iv:7GKatHDrlpBR0P5FrO5N3lsba38BQrZPl2zdu0qcD5U=,tag:gPxMjp/ZigPh437xTStqlg==,type:str]
sops:
    age:
        - recipient: age1wf5fe39ddk2dwh5ute445pfsv3wl68hx2j7f9phh90zvgnsk8sdsdj0zx7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWL3k0bVV1ZVNLbzFQVlJr
            RzdFaVBLVlRFSWFLQmFjSUFvREtzY1FMRVRvCkJrOGZPWHRoTGJrbGdxQkNaS3N2
            Q1JQc05ZR2psU0FieDhXaDRhcG4wVVkKLS0tIFVwc0k3MW55NjlJWUZnRkZxL2VF
            eDcyZlJGeWlaNHFUSDg1K0ZMcHQzZVEKoMQC0alBv7LsFmn7AV7dpzMXzYi74ps+
            AJif9du2y2HF6EdLos46kqyqf8o421BDCwf6RGn+4syl6YKDt7OZcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T11:41:34Z"
    mac: ENC[AES256_GCM,data:ozD6PbNV+LAUVLV6NQaKAtRhJzCwMa1isQtJYaIVeW8ke6X264TmttMCq9YXQn9T1AHUzyqiCU++bn92CoDP63nii60+Bbv1WTGARAXE0Zsr5S5d5U5VyQA6WZ1h5qDN99+HGOn0B9CoBGfN1+Z5xJ9P09hD/8/9xX1Cqanum0M=,iv:hzZt2lg3xs1EDCAXgHV2fbQDpDZXyk49dm9VJs9PA4o=,tag:8er2fjZgJuoc+4HIQ6xGDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
