apiVersion: v1
kind: Secret
metadata:
    name: your-spotify-secret
    namespace: your-spotify
stringData:
    SPOTIFY_PUBLIC: ENC[AES256_GCM,data:1Erx/jwT6++VPdQVxXqWh2Dc9xs48fvGF5YOlikdbyg=,iv:GM8nw7q26BvPUXaNBowsDzZapcrTTUSAnf/KH1X9ELc=,tag:B91qFz5D4GR6Fwla+0oXWg==,type:str]
    SPOTIFY_SECRET: ENC[AES256_GCM,data:l0JvHDUEBA5xysgBJDYnbEcfjXHlE8Bmufr4E1CGzH8=,iv:Nhq0Zo7H3AI+0WY0yj0p8/muxy4sD6uhF6gCT0qdV/o=,tag:Nkx3lKinby100aRWp2R5DQ==,type:str]
sops:
    age:
        - recipient: age1wf5fe39ddk2dwh5ute445pfsv3wl68hx2j7f9phh90zvgnsk8sdsdj0zx7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUWgzZGlLZ21BbFFjbTI1
            Nnd1dGtRVll4RitHWHFZL0xoUlRzYVBJSXc0CmFVZitqeG13QXlzRFR4NjlUUExN
            ZU50WlZIanhnVG53SkFIelBkYlhIRG8KLS0tIFZKdWNFOTVoRFVzaXEvc3dDQkJj
            MTN0aGphZGlmZ0gzcEtQK01tSTlSYVUKVsOphqOINBXL9kDu6lopxEMocQP80w6/
            UfPgU4K90qDBa4jQvUuYmIy36BFUdyBFP1c5RWCboNVB//MIPkkigg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T10:17:06Z"
    mac: ENC[AES256_GCM,data:Zmd5XBX+bS4wmpG2AxZSgyEZS4zTR1NavFHR7RR0m+ArzorJY6+RkMdrY6wiEvNMQIxFXe4LIbOoAy5ZJvVHDN+fYba+ofZxXeUgV/tg1pnLDWYZmffNAYQ76rJEMj4hgg+Wq7tfBsR+GzVo/3kq2AV0Hi7vnQDWonzjoLp8KFI=,iv:ZP8nD3gDXDnqa/i6mt2djVEaZF0POL3yfufzt4jmQec=,tag:X5iR2wu2wovu5cBYe3Hv9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
