apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-spotify-mongo
  namespace: your-spotify
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: your-spotify-mongo
  template:
    metadata:
      labels:
        app: your-spotify-mongo
    spec:
      nodeSelector:
        kubernetes.io/hostname: pve
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: your-spotify-mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: your-spotify
spec:
  selector:
    app: your-spotify-mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-spotify-server
  namespace: your-spotify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-spotify-server
  template:
    metadata:
      labels:
        app: your-spotify-server
    spec:
      containers:
        - name: server
          image: yooooomi/your_spotify_server
          ports:
            - containerPort: 8080
          env:
            - name: API_ENDPOINT
              value: http://localhost:8080
            - name: CLIENT_ENDPOINT
              value: http://localhost:3001
            - name: MONGO_ENDPOINT
              value: mongodb://mongo:27017/your_spotify
            - name: SPOTIFY_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: your-spotify-secret
                  key: SPOTIFY_PUBLIC
            - name: SPOTIFY_SECRET
              valueFrom:
                secretKeyRef:
                  name: your-spotify-secret
                  key: SPOTIFY_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: your-spotify-server
  namespace: your-spotify
spec:
  selector:
    app: your-spotify-server
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-spotify-web
  namespace: your-spotify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-spotify-web
  template:
    metadata:
      labels:
        app: your-spotify-web
    spec:
      containers:
        - name: web
          image: yooooomi/your_spotify_client
          ports:
            - containerPort: 3000
          env:
            - name: API_ENDPOINT
              value: http://localhost:8080
---
apiVersion: v1
kind: Service
metadata:
  name: your-spotify-web
  namespace: your-spotify
spec:
  selector:
    app: your-spotify-web
  ports:
    - port: 3001
      targetPort: 3000
