apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: newt
  namespace: newt
spec:
  interval: 1h
  chart:
    spec:
      chart: newt
      sourceRef:
        kind: HelmRepository
        name: fossorial
        namespace: flux-system
  values:
    newtInstances:
      - name: main
        enabled: true
        auth:
          existingSecretName: newt-cred
          keys:
            endpointKey: PANGOLIN_ENDPOINT
            idKey: NEWT_ID
            secretKey: NEWT_SECRET
        nodeSelector:
          kubernetes.io/hostname: acer-8gb
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: newt-newt-main
            patch: |
              - op: add
                path: /spec/strategy
                value:
                  type: Recreate
              - op: add
                path: /spec/template/spec/hostNetwork
                value: true
              - op: replace
                path: /spec/template/spec/dnsPolicy
                value: ClusterFirstWithHostNet
              - op: add
                path: /spec/template/spec/containers/-
                value:
                  name: proxy-amneziawg
                  image: alpine/socat:latest
                  args: ["TCP-LISTEN:9351,fork,reuseaddr", "TCP:100.96.128.10:9351"]
              - op: add
                path: /spec/template/spec/containers/-
                value:
                  name: proxy-node-exporter
                  image: alpine/socat:latest
                  args: ["TCP-LISTEN:9100,fork,reuseaddr", "TCP:100.96.128.10:9100"]
