apiVersion: v1
kind: Secret
metadata:
    name: newt-cred
    namespace: newt
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:8MTQw2VmI5FBkcci1eLfHh3A7bbm5h7odOqGYg==,iv:5r+WhHWCPj7PRbMcCg8SgbXyAz3PZeViXAeSGN5TVA4=,tag:Gd83lNjOZoFRuQFiGqfDCA==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:oixtvQoIDkojLcjh+Nmn,iv:Mmq4df6KHEwO6B2reExY7uwq52dD+hrfd2Kr+pMMnUM=,tag:kOgcfJUBuGNerFku8mwNbw==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:YxjMNSvpHaFHFK61E1eJ999UDwqANVQYsm4oV+GQ0CQqinVTP7PLJES55GiOQ8cp,iv:pPA4CQV99nJvWq2Twwrxl1FbDCzGgOyaqeOhUsAd/Qo=,tag:CUuhCONbrTVY4/MBhWmFYg==,type:str]
sops:
    age:
        - recipient: age1wf5fe39ddk2dwh5ute445pfsv3wl68hx2j7f9phh90zvgnsk8sdsdj0zx7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWjBmdGhnMjZWVHlvZXVC
            ZjZLYXR3K1VmV2NoTENYOVFUVmRFWGZjYm1jCmhRM0ZIdW9TMVRBR0VWVmN1N2Rs
            MmVDOGlVek9rQ0JNTlU3RmN2bTlESlkKLS0tIE84RDJ3OHRST0RjWU5wNFhaS3Vp
            ZEpCS044WS95NXlGa25aL3pOVytoUEEKYDgrayce65Q/1upfengQQlH7a4TusS8o
            EhJrSCbPK+hPCMTuYDtVXZfOJUWQjzbzF5GdPXQLt4I/uauETlCpow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T12:20:54Z"
    mac: ENC[AES256_GCM,data:xgf7qcR1LBSQ+AGCYIzZrTEVqRC7kCGLLI0yC3qghJh+qDc09/7DGEZqQUgG/YcRNPMSkMI6Kw0Z/S525oFTTUHx/tHvjWynI6oEXU7jZYXR2WG7i8NSJA4wDGNWpfmPkz80THbB4uUYY7ozoaG629ni4VayhAv8WPCx46wADlM=,iv:Xa5wx1svpkxZ/+caoHGjUywxQn8+9PJXc7E76oPouUw=,tag:jHJzer+m6XtSs5IP+JZ2VQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
