apiVersion: apps/v1
kind: Deployment
metadata:
  name: ente-minio
  namespace: ente
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ente-minio
  template:
    metadata:
      labels:
        app: ente-minio
    spec:
      nodeSelector:
        kubernetes.io/hostname: asus-8gb
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: ente-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ente-secret
                  key: MINIO_ROOT_PASSWORD
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - mountPath: /data
              name: minio-data
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: ente-minio
---
apiVersion: v1
kind: Service
metadata:
  name: ente-minio
  namespace: ente
spec:
  selector:
    app: ente-minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
