apiVersion: v1
kind: Secret
metadata:
    name: ente-secret
    namespace: ente
stringData:
    ENTE_DB_PASSWORD: ENC[AES256_GCM,data:qqC1M/Yf2MYc,iv:vB9N5T+y1FSZwA8n7gXKY49mKjR9h6yKxpfQYmSmVEY=,tag:vZnaPKSHKxrvyeEvWstw0w==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:4A4AbnNVaoJ7sOo=,iv:0Wkcy7f10dmB+ZdT1+JWuiZ6CqiKegI8RCGCud+lAlA=,tag:88mZ2xyYxp8Zxc0+PjZqFw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:aj8+kfNlefrM,iv:Vxv5OrCMS8wJqFa9KuGAgBiBqMhB9p585gWKeJNHcF0=,tag:RylXIs+t2UgWTb810bYpzA==,type:str]
    ENTE_KEY_ENCRYPTION: ENC[AES256_GCM,data:rFoLu9HnPrxKTGmhp7rQj3r5aHtKaUb/Kn0bOiCg8/0h4fsxA2wMS7VxdZw=,iv:f+uLDVZ2UV7b5cCsbfLVR3jxn5bOVSEfUWDQb30ldmc=,tag:cMupFhm0aR+aMV4ZhDnwhA==,type:str]
    ENTE_KEY_HASH: ENC[AES256_GCM,data:qgmjiv9VxvNJtOL65OSgR7CZVlS1Gpl95LlmP9ZPEr0=,iv:jlLrmGQYJpkOVJSDAqMfqWIp3v04dhFdN+Px/Y0VHgM=,tag:/6XNA/KIHLNxP0KmsDJPqw==,type:str]
    ENTE_JWT_SECRET: ENC[AES256_GCM,data:rfTH7u0Wt8bEeX38IRLvJP8WIQNb1oGj1BZCoK2DVqAi0OPZq9R1zj0VZqTAbnLy9g85xA+FBcPM3K0KFtJ1sA==,iv:6mXULiqCdYnKCWfzeZRoXzfQweC3q5XLfZMaUZUjc1A=,tag:+X92nqXPIoOseGQO8+Kr6g==,type:str]
sops:
    age:
        - recipient: age1wf5fe39ddk2dwh5ute445pfsv3wl68hx2j7f9phh90zvgnsk8sdsdj0zx7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUzFUbWluVGxZb01rVXJv
            ZDFrbEpWNmZWQk1EVUVxUFpiTjVXaTR2WmhrCmxpREpXWGkxVVV6M1BTMmRiNUV3
            OExVREhVby93dU5la0N0djllRko3M0UKLS0tIG9hdXBJSzFtWHpQS2hJUkE3UU55
            dVNZa0x0V0JwS3J6djlhbUR2Z1MxNnMKKBi3/hsrTbclptzH6hSvIvaFE2CNFglm
            QKTbSxN5r7aGjr/puAXHJgYClvxcm62CMGQgAwuj0KPDdesO0rB0aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T19:03:32Z"
    mac: ENC[AES256_GCM,data:VKeZbvIrTNLg7cGB4RDyzTwZGXLtz8kRScUBMAnvXjUeDDzZzWsHM4nPN0tVdguxLE394f0sn5daWlMKuTayEc93TNSlfbc8FXcOvwBp/ySsJuzZF6svhsRrGjhnnPhyHoHk3yoXalXkLcoxGc0bo5H9IZF5z7iM9Whusz2ML1M=,iv:avJ56cxFoHt6qiHGwyblIQgE5arehNec1RHVQddnr94=,tag:qN4QI+dyEitohYWotZq3SA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
