apiVersion: v1
kind: Secret
metadata:
    name: ente-secret
    namespace: ente
stringData:
    ENTE_DB_PASSWORD: ENC[AES256_GCM,data:ayU2ISil3FZ8,iv:zX0Qc7r1Y6iaRNm/QsZTVI7+ZMhiKpdsracgLIpEpGY=,tag:mZpBT8mIJYp5lZUDToA26A==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:omE+q+0pCnG+PWs=,iv:0ty0o/uTV9M3cz9LKlUvWrxtKnfhVF9Jv/ECveWyMdc=,tag:ShvrACvcEBWNNDiH6kvl6Q==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:BInXgLtQxozg,iv:E3tEViXk7vrm1tPmseX95nGslS9BPvv1QS525300n+s=,tag:lt9CKpVnTSBd5opzAIaMhQ==,type:str]
    ENTE_KEY_ENCRYPTION: ENC[AES256_GCM,data:YHmHxiTYMCGF0a3occcA27Y6inIuRQjKgkj3nMXkfDs=,iv:kB/2Yu8EwvAbRwEX/QI39Xr/P17SBlv9rZqBdzuUb9I=,tag:Cm26RCcnZWNoinUvEMkQ/A==,type:str]
    ENTE_KEY_HASH: ENC[AES256_GCM,data:aHTtuhbJuV1TZ3TvO/7qUOp/uTE4C7fJDNGMztndacI=,iv:3vh3XK1yxOEOBNSgw1mIgZOAKhckVLENW9fF2rSik94=,tag:bFv7MxN9LruzIn6LdODdyg==,type:str]
    ENTE_JWT_SECRET: ENC[AES256_GCM,data:vW9DsufUcN4xd/0Aj2GLGme9kq8biEQpdeOTJrzd5nB39Gaa4fVkFhd6sc58YGTv6NTo/L1m7XweYdqkJJjxIA==,iv:Ly5eIlNrlCFPyEmT813/Gk51ph7S5SVEKhhR3N/Lq2g=,tag:y/8VfsMiyBzNLJoTGu52OA==,type:str]
sops:
    age:
        - recipient: age1wf5fe39ddk2dwh5ute445pfsv3wl68hx2j7f9phh90zvgnsk8sdsdj0zx7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcWlOSk9yS0xXcVNwTUE0
            dnNKeW41a1I4N0xPYzZqc21OcExuR0VtUzJvCkk0VmlmbWllU3lYSXU4S3ZWNzIv
            SGFha0Y4bmZUUncrWm5WSXh5QVpzcmcKLS0tIENxME52MWQwZ2RoQy9XUlNBT09D
            ckVOd0dqVVZUbDlVLzZYejdjNFc5NDgKrPhSjqWQw5Tu3GBpSGiOTiMcqehaugPs
            kQ5TtlUdzyQl5xwnL5uBeGvgCUxQZy9zsWu5bY1KcbdnY9DK0bDA9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T18:41:28Z"
    mac: ENC[AES256_GCM,data:WR8+s1OxLvSegHNy2qgJqp5G9VpKjiSM1kt+VI0+g7qUiRqJ4ALC5AE72SRHPs25kreo3W7tJUDGR49hf0r7tzQVn+nwbRbTWNsQkadXYRAvfuJB9RmtZjzApfl9NTacbJtM/bvggwcMhaztqQhf9I49fyTnJ0zupynx1vhp0f0=,iv:uSpifRoeID24Yb7Q2gpWohjWIGzAd3Rq5isYyRtqwJ8=,tag:YWnHLQ1Nd55DLIcojLyKcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
